export { default as clamp } from './clamp';
export { default as toBoolean } from './toBoolean';
export { default as range } from './range';
export { default as toPercent } from './toPercent';
export { default as getColorNameByIndex } from './getColorNameByIndex';
export { default as isUltimate } from './isUltimate';
export { default as msToTime } from './msToTime';
export { default as getLevelExperiencePercent } from './getLevelExperiencePercent';
export { default as getHeroRespawnTime } from './getHeroRespawnTime';
