name: 🚀 FTP Deploy FRC Prod

on:
  workflow_dispatch:
jobs:
  ftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: /w3overlay
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - run: npm ci
      - run: npm run build --if-present

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.frc_ftp_server }}
          username: ${{ secrets.frc_ftp_user }}
          password: ${{ secrets.frc_ftp_password }}
          local-dir: ./build/
          server-dir: /public_html/w3overlay/
