name: 🚀 FTP Deploy Prod

on:
  workflow_dispatch:
jobs:
  ftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: /w3overlay
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - run: npm ci
      - run: npm run build --if-present

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: "FrenchCraft"
          server: ${{ secrets.sftp_server }}
          port: ${{ secrets.sftp_port }}
          ssh_private_key: ${{ secrets.sftp_key }}
          local_path: "./build/*"
          remote_path: "/FrenchCraft/w3overlay/"
          args: "-o ConnectTimeout=5"
