on:
  push:
    branches: [main]
  workflow_dispatch:
name: 🚀 Deploy website on push
jobs:
  ftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5 
        env:
          PUBLIC_URL: /w3overlay
      - run: npm ci
      - run: npm run build --if-present

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.cluster029.hosting.ovh.net
          username: tinkern
          password: ${{ secrets.ftp_password }}
          local-dir: ./build
          server-dir: /wwww/resume/w3overlay
          dry-run: true
